---
- hosts: ubuntu
  become: yes
  tasks:
    - name: Install if it is Ubuntu system
      apt:
        name: wget
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: make dir in the home dir of the /home/ansible/temp
      file:
        path: /home/ansible/temp
        state: touch
      when: ansible_distribution == "Ubuntu"
    - name: debug the variable
      debug:
        msg: "My name is {{ myname }}"
