---
- hosts: all
  become: yes
  tasks:
    - name: uninstall tree and nmap 
      apt:
        name: "{{ item }}"
        state: absent
      with_items: ["tree","nmap","wget"]
      when: ansible_distribution == "Ubuntu"  
    - name: uninstall tree and nmap
      yum:
        name: "{{ item }}"
        state: absent
      with_items: ["tree","nmap","wget"]
      when: ansible_distribution == "RedHat"
        


